version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
      - PORT=5001
      - REDIS_TLS=false
    depends_on:
      - redis 