export const ACTIONS = {
    JOIN: 'join',
    JOINED: 'joined',
    DISCONNECTED: 'disconnected',
    CODE_CHANGE: 'code-change',
    SYNC_CODE: 'sync-code',
    SYNC_CODE_RESPONSE: 'sync-code-response',
    REQUEST_CODE: 'request-code',
    CURSOR_CHANGE: 'cursor-change',
    SELECTION_CHANGE: 'selection-change',
    CURSOR_LEAVE: 'cursor-leave',
    REQUEST_CURRENT_CODE: 'request-current-code',
    SEND_CURRENT_CODE: 'send-current-code',
    LANGUAGE_CHANGE: 'language-change',
    REQUEST_LANGUAGE: 'request-language',
    ROOM_LANGUAGE: 'room-language',
};